name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk
          pip3 install buildozer cython==0.29.33
          buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: elevate-2023-apk
          path: bin/*.apk
